name: Go
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true
      - name: Install libpcsc
        run: sudo apt-get install -y libpcsclite-dev pcscd pcsc-tools
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./inmemoryks/... --coverprofile=coverage.out  -timeout 10s -v > testResults.txt
      - name: Format coverage
        run: go test  --coverprofile=coverage.out  -o coverage.html
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: testResults.txt
      - name: Upload Go coverage report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage-report
          path: coverage.html
